version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://recipick_user:recipick_password@db:5432/recipick_db
      - ENVIRONMENT=production
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - CORS_ORIGINS=http://144.24.94.13:3000,http://144.24.94.13:8000
    depends_on:
      - db
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://144.24.94.13:8000
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=recipick_db
      - POSTGRES_USER=recipick_user
      - POSTGRES_PASSWORD=recipick_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  postgres_data: